name: Build DiscordNotify JAR
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build
        run: ./gradlew shadowJar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: DiscordNotify
          path: "build/libs/DiscordNotify-*-all.jar"